openapi: 3.0.3
info:
  title: E-Commerce Product API
  description: |
    This API provides endpoints to retrieve product details and related products.
  version: 1.0.0
paths:
  /products/{productId}:
    get:
      summary: Get Product Details
      parameters:
        - name: productId
          in: path
          description: ID of the product to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Product details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          links:
            RelatedProducts:
              operationId: getRelatedProducts
              parameters:
                productId: $response.body#/productId

components:
  schemas:
    Product:
      type: object
      properties:
        productId:
          type: integer
        name:
          type: string
        price:
          type: number
        description:
          type: string
      required:
        - productId
        - name
        - price
